name: "blue_grass"

services:
  nginx:
    container_name: "blue_grass_server"
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/laravel
    depends_on:
      - mysql
      - php
  php:
    container_name: "blue_grass_php"
    build:
      context: docker/php
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/laravel
  mysql:
    container_name: "blue_grass_db"
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - docker/env/mysql.env
    volumes:
      - db_data:/var/lib/mysql

  composer:
    container_name: "blue_grass_composer"
    build:
      context: docker/php
      dockerfile: composer.Dockerfile
    volumes:
      - ./:/var/www/laravel
  artisan:
    container_name: "blue_grass_artisan"
    build:
      context: docker/php
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/laravel
    entrypoint: [ "php", "/var/www/laravel/artisan" ]

volumes:
  db_data:
